FROM %%FROM%%

MAINTAINER timo.heister@gmail.com

# get deal.II repo
ARG VER=master
ARG BUILD_TYPE=DebugRelease

RUN git clone https://github.com/dealii/dealii.git dealii-$VER-src && \
    cd dealii-$VER-src && \
    git checkout $VER && \
    mkdir build && cd build && \
    cmake -D DEAL_II_WITH_MPI=ON \
          -D DEAL_II_COMPONENT_EXAMPLES=OFF \
          -D DEAL_II_CXX_FLAGS_DEBUG='-O3' \
          -D CMAKE_INSTALL_PREFIX=~/dealii-$VER \
          -D CMAKE_BUILD_TYPE=$BUILD_TYPE \
	  -G Ninja \
          ../ && \
    ninja install && \
    ninja test && \
    cd .. && rm -rf build .git

ENV DEAL_II_DIR $HOME/dealii-$VER
