FROM %%FROM%%

MAINTAINER timo.heister@gmail.com

USER root
ADD candi/ $HOME/candi/
RUN chown -R $USER:$USER $HOME/candi/
USER $USER

RUN \
  cd candi && \
  ./candi.sh -j8 \
	--platform=deal.II-toolchain/platforms/supported/ubuntu16.platform \
	--prefix=$HOME/libs \
	--packages="load:dealii-prepare once:arpack-ng once:opencascade once:parmetis once:superlu_dist once:hdf5 once:p4est once:trilinos once:petsc once:slepc" &&\
  rm -rf $HOME/candi $HOME/libs/tmp

# I don't know how to import env vars from the configuration folder.  This
# probably doesn't work at all, because we don't use bash but sh and so we can
# not use 'source' or any of the bash startup files. Manually export the paths
# here instead:
RUN cat ~/libs/configuration/* | grep export | sort

ENV ARPACK_DIR=/home/dealii/libs/arpack-ng-master
ENV HDF5_DIR=/home/dealii/libs/hdf5-1.10.1
ENV METIS_DIR=/home/dealii/libs/parmetis-4.0.3
ENV OPENCASCADE_DIR=/home/dealii/libs/oce-OCE-0.18.2
ENV P4EST_DIR=/home/dealii/libs/p4est-2.0
ENV PARMETIS_DIR=/home/dealii/libs/parmetis-4.0.3
ENV PETSC_DIR=/home/dealii/libs/petsc-3.7.6
ENV SLEPC_DIR=/home/dealii/libs/slepc-3.7.3
ENV SUPERLU_DIR=/home/dealii/libs/superlu_dist_5.1.2
ENV TRILINOS_DIR=/home/dealii/libs/trilinos-release-12-10-1
